# --- 保持你原本华丽的特效账本 ---
include dank-tabs.conf
include dank-theme.conf
window_padding_width 5
hide_window_decorations yes
background_opacity 0.8

# --- 字体主配置 (完全继承你的 JetBrains Mono) ---
font_family      JetBrainsMono Nerd Font
font_size        10.0

# --- 防御机制：防止 Fedora 乱借不丹文导致字间距注水 ---
# 强制让 Fedora 系统自带的等宽中文字体和刚刚手动平移的更纱 UI 兜底
fallback_fonts   NotoSansMono-Regular, Sarasa UI SC

# 强行将 Starship 极客符号和不规范的宽字符锁定为 1 倍标准宽度
narrow_symbols U+F000-U+F2FF,U+E0A0-U+E0A3,U+E0B0-U+E0C8,U+E700-U+E7C5,U+F400-U+F4A9,U+F0DB 1

# --- 完美继承你其余的极客参数配置 ---
remember_window_size no
confirm_os_window_close 0
shell fish
cursor_trail 1 
cursor_shape block
shell_integration no-cursor
